module.exports = [
	{
		title: '1000 characters',
		text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod massa vehicula molestie suscipit. Sed ut ante felis. In faucibus pellentesque lacus sed faucibus. Pellentesque pulvinar in erat quis cursus. Nullam lobortis sagittis gravida. Quisque maximus nulla non mauris gravida, nec ornare diam fringilla. Vivamus aliquet lacus ut lorem aliquam molestie. Mauris tincidunt, arcu vitae ultricies luctus, turpis lectus pharetra est, quis euismod nibh massa eu arcu. Duis placerat, felis nec finibus sagittis, ipsum dui scelerisque nibh, sit amet lacinia ipsum eros et massa. Sed tempor, tortor eget lobortis tempor, urna lacus cursus nibh, ut lobortis eros libero sed elit. Cras est augue, tincidunt nec diam vitae, consequat euismod ex. Donec sed pharetra tellus. Proin varius velit velit. Cras aliquam est ut turpis interdum tristique.

		Donec rhoncus tempus augue ac luctus. In vitae molestie erat, sit amet viverra elit. Maecenas tristique finibus sem, nec iaculis leo. Phasellus ante odio.`
	},
	{
		title: '5000 characters',
		text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla leo ut massa molestie, sed volutpat lacus semper. Sed tincidunt nec quam sit amet feugiat. Curabitur tincidunt est nisi, et laoreet nunc blandit id. Morbi sagittis, tortor eget bibendum feugiat, arcu ex hendrerit orci, vel dignissim mi magna a augue. Nulla vel orci diam. In consequat nisi mi. Curabitur venenatis lorem eu laoreet cursus. Etiam quis ex ligula. Pellentesque imperdiet ut dui at mollis. Duis efficitur blandit dapibus. Nullam sit amet libero imperdiet, malesuada erat nec, aliquet mi. Ut eget dolor fermentum, ullamcorper ex quis, ullamcorper ante.

		Fusce congue ac tortor in fringilla. Quisque eget gravida est, et tincidunt diam. Sed vitae libero eu metus facilisis semper eget id ligula. Praesent molestie massa eget neque vehicula sagittis. Vivamus turpis massa, laoreet ut egestas in, dictum vel arcu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed nisi justo, iaculis eget augue eu, laoreet interdum nisi.

		Sed varius nunc et enim gravida, ac interdum nunc fringilla. Etiam gravida urna consequat quam egestas euismod. Proin placerat magna tortor, id dictum sapien imperdiet sit amet. In ornare sapien erat, ac vehicula nunc malesuada euismod. Duis aliquam nunc nec dui auctor, sit amet tristique felis dignissim. Maecenas at vestibulum turpis, ut consequat elit. Proin vel eleifend mi, eget pretium eros. Duis enim dolor, pretium at metus at, ornare vestibulum augue. Vestibulum molestie dui in neque ultricies, et sagittis sapien scelerisque. Quisque aliquet faucibus fringilla. Aliquam condimentum eros nec lobortis cursus.

		Vivamus erat mauris, congue ut risus id, mattis tristique lorem. Nunc imperdiet interdum placerat. Etiam blandit vehicula sapien ut bibendum. Suspendisse consectetur eros a nibh iaculis, et scelerisque metus commodo. Nullam id enim leo. Suspendisse venenatis sollicitudin metus quis porttitor. Nullam suscipit neque eu nunc lobortis pellentesque. Quisque ornare mi sed dictum placerat. Curabitur aliquam non orci et rutrum. Sed quis libero elit. Phasellus egestas orci sit amet semper sagittis. Aenean volutpat lorem a tempus fringilla. Nunc ultrices nisl diam, a scelerisque lacus venenatis vitae. Ut urna lorem, scelerisque sit amet aliquam vitae, egestas id sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus dui dui, tincidunt sed facilisis id, congue eget quam.

		Donec in congue metus. Sed neque nunc, efficitur et varius sed, fringilla nec augue. Integer gravida aliquam elit, et scelerisque orci volutpat ut. Nullam felis risus, elementum ac nisi vitae, rhoncus molestie est. Quisque sapien velit, congue ac purus et, efficitur consequat elit. Mauris fringilla, elit mollis blandit ultrices, nibh lacus suscipit elit, eget porttitor augue sem vitae dui. Fusce nec arcu ac augue lobortis mollis. Duis lacinia, eros a ullamcorper tincidunt, enim leo tincidunt eros, sed posuere dolor ex sit amet erat. Cras in leo velit.

		Vivamus ac ullamcorper leo. Aenean mattis pretium dolor finibus ullamcorper. Sed vel dapibus metus, in lacinia odio. Suspendisse posuere enim elementum eleifend laoreet. In tellus mi, tempus et ultricies non, ultrices in tortor. Integer faucibus ac diam at sagittis. Integer mauris diam, condimentum sed euismod et, suscipit feugiat magna. Nulla at lacus lacinia, euismod orci at, pretium velit.

		In elementum nibh a quam iaculis consequat. Etiam eu gravida ligula. Aenean at nisi ante. Cras quis nunc eu sem congue lacinia. Cras lacinia orci a ex aliquam tincidunt sed ut orci. Ut non metus nunc. Donec porta efficitur ante a sodales. Phasellus eget elementum felis. Aliquam sed hendrerit quam. Nulla justo libero, cursus non tempus id, consectetur eget orci. Suspendisse pretium nisl sed lacus blandit sodales sed et nulla. Mauris placerat ex ipsum, a euismod ex ornare et. Nam euismod accumsan porttitor. Sed nisl sapien, congue et augue eget, fermentum maximus nulla. Morbi ante dui, tincidunt ac eros facilisis, faucibus ullamcorper libero. Duis leo lorem, tempus quis ipsum in, placerat pretium eros.

		Fusce faucibus tellus id mauris aliquet pharetra. Mauris sed bibendum nunc, non fringilla justo. Praesent sed lacus elit. Nullam ut nisl lectus. Integer ac lorem nisl. Aliquam posuere arcu non eleifend vehicula. In sit amet libero eget dui ornare laoreet nec ultrices nulla. Nullam aliquet eros eu ante consequat, eu laoreet lorem sodales. Vivamus eleifend sem nunc, eget facilisis metus rutrum et. Morbi elit libero, ullamcorper sed nisi a, egestas sagittis lectus. Pellentesque at urna quis nibh dapibus malesuada in eu elit. Ut vel lacus et neque consequat pharetra. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent non porttitor tellus. Mauris dictum, risus ac posuere sodales, velit nulla placerat mauris, quis malesuada ante tellus a metus. Duis quam purus, congue at sapien id, fringilla congue et.`
	},
	{
		title: '250 words',
		text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tincidunt ac nunc at rutrum. Phasellus laoreet euismod efficitur. In gravida fermentum justo ac consequat. Vivamus et diam sed dolor finibus consectetur. Praesent id diam ac nulla commodo venenatis et id augue. Vestibulum semper accumsan neque a pellentesque. Donec accumsan nisi ex, eu suscipit ipsum dapibus sit amet.

		Integer quis ultricies lacus. Cras a pulvinar turpis. Morbi iaculis fringilla rhoncus. Aenean rhoncus mauris sit amet cursus dictum. Pellentesque dapibus, turpis a vulputate lobortis, tellus leo ullamcorper magna, a fermentum tortor ipsum sed urna. Suspendisse felis lorem, semper id erat sed, ornare consectetur mauris. In congue massa ac ante varius condimentum. Proin ac ipsum et lectus blandit malesuada. Integer a purus eget dui elementum hendrerit vel nec risus. Vivamus aliquam at sem nec molestie. Donec placerat nibh nec odio scelerisque, ac efficitur ligula placerat. In hendrerit, lorem vitae tincidunt pellentesque, elit sem tempor ex, eu euismod nunc elit in lacus. Morbi quis accumsan est. Morbi risus massa, iaculis ut leo aliquam, volutpat molestie quam.

		Duis tincidunt scelerisque fringilla. Aliquam justo risus, aliquam nec neque a, aliquam ultrices ex. Sed vulputate viverra mauris id lacinia. Donec tristique mattis lectus, ut dictum lacus tincidunt et. Suspendisse vitae risus nunc. Etiam sit amet enim sed quam porta auctor. In in accumsan mauris. Sed maximus iaculis neque in suscipit. In consequat, nisi sed congue iaculis, nisl lectus volutpat neque, vel ultricies felis arcu sed risus. Aliquam porta sapien ut felis tincidunt pretium. Nam non nulla id.`
	},
	{
		title: '1000 words',
		text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce suscipit nunc eros, a malesuada turpis vestibulum a. Vivamus eu cursus libero. Vestibulum molestie turpis a est maximus interdum. Donec bibendum, massa eget sodales sodales, magna eros consequat magna, eu lobortis elit est ac risus. Nulla facilisi. Ut placerat libero at dui fringilla bibendum. In hac habitasse platea dictumst. Fusce tristique est elit, ut laoreet nisi consequat a. Vestibulum eu sodales augue. Nam vitae tortor vel sapien placerat egestas vehicula eu urna. Phasellus ullamcorper vehicula mauris ut facilisis.

		Quisque ante ex, commodo vel tortor in, bibendum maximus est. Nulla eleifend mauris turpis, nec elementum urna scelerisque in. Etiam dignissim quam in quam euismod porttitor. Integer interdum vitae ligula a tincidunt. Etiam ac pretium nisi, efficitur malesuada libero. Pellentesque ut tellus nulla. Aliquam gravida lacus eros, et porta dolor egestas id. Curabitur maximus pulvinar sem id ullamcorper. Duis gravida aliquet dui sed ultricies.

		Maecenas est ante, accumsan eu facilisis ultrices, placerat sit amet est. Nullam nibh urna, feugiat ac imperdiet ac, tincidunt in lectus. In ipsum nisl, dapibus ut neque a, facilisis varius velit. Curabitur odio erat, ultrices non ligula et, sagittis dictum sem. Pellentesque vel nisl at orci dapibus aliquet. Etiam cursus augue eu ante ullamcorper hendrerit. Vestibulum in neque sem. Vestibulum ultrices accumsan facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin pulvinar ac augue et hendrerit.

		Nunc vitae sodales eros. Pellentesque nec eros vitae orci posuere dictum. Donec porta nisi id egestas lobortis. Phasellus consectetur tristique magna at dapibus. Ut vitae lacus scelerisque, congue metus sit amet, maximus erat. Etiam vel convallis leo. Sed neque quam, iaculis eget nulla non, tincidunt aliquam arcu. Sed ex arcu, dignissim ac elit ultricies, sodales facilisis arcu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum luctus orci id condimentum facilisis. Sed pretium, nulla non rhoncus pellentesque, tellus purus maximus arcu, vel luctus massa est quis purus. Vestibulum vestibulum sapien nulla.

		Nullam convallis orci mi, a laoreet dolor maximus sed. Suspendisse rhoncus malesuada dolor et dignissim. Duis quis efficitur ligula. In quis viverra leo, at aliquam orci. Duis sit amet lorem et massa aliquam varius eget id sem. Etiam ut maximus mi. Praesent ultrices felis ut nulla placerat, eu mattis elit mollis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi aliquam diam nisi, nec posuere dolor vulputate eu. Proin auctor diam non eros blandit, ut efficitur tortor pulvinar. Ut rhoncus ullamcorper feugiat. Vivamus scelerisque euismod varius. Pellentesque lacinia nisl non odio iaculis iaculis id eget massa. Cras consequat diam ut porttitor facilisis. Cras faucibus eget quam in rhoncus.

		Suspendisse ultricies placerat metus at ultrices. Ut vitae orci scelerisque, porttitor ante eu, suscipit nisi. Integer mattis commodo justo at vehicula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed tristique euismod lobortis. Fusce vitae turpis felis. Praesent sem libero, cursus ut est et, consequat posuere nunc. Sed sit amet ullamcorper turpis, quis gravida orci. Fusce fringilla vitae ligula sit amet maximus. Aliquam erat volutpat. Phasellus et dui non arcu dapibus finibus. Suspendisse potenti. Phasellus vehicula eget lacus non mollis.

		Proin congue dolor sit amet ipsum auctor, et pharetra mi laoreet. In dictum lectus sit amet placerat euismod. Proin ornare porta porta. Duis laoreet, erat at aliquet varius, magna ante pharetra elit, quis ultrices libero nisl a erat. Suspendisse sit amet iaculis tellus. Mauris eu erat et est vulputate hendrerit vel vitae mauris. Vestibulum scelerisque ex ac enim feugiat auctor. Nulla ac erat vel mauris dapibus gravida. Mauris feugiat urna a tellus ultricies malesuada. Duis vel ex et nunc tincidunt bibendum. Aenean vel efficitur dui, non ultrices erat.

		Suspendisse accumsan ornare hendrerit. In venenatis felis ac orci porta, at aliquam elit varius. Aliquam et purus sit amet elit luctus congue. Phasellus lacinia mollis velit vitae ultrices. Sed id molestie ligula, non ullamcorper sem. Maecenas id suscipit elit. Vivamus vitae arcu ut orci fringilla rhoncus. Praesent eleifend sagittis mi vitae porttitor. Aliquam sed faucibus est. Vestibulum pulvinar ligula metus, commodo viverra justo dictum a. Phasellus arcu tortor, rhoncus quis felis non, auctor congue ligula. Curabitur quis diam ante. Nam tempor nec est at placerat. Nulla nisi erat, bibendum non consequat in, egestas et sem. Ut ullamcorper vulputate dui eu varius.

		Nunc viverra, est in blandit cursus, metus ex interdum nisl, vel vehicula nibh lectus vitae dui. Pellentesque tempor risus et diam euismod ultricies. Nullam lacinia pellentesque nisi, blandit sollicitudin est finibus sed. Vestibulum dignissim in ipsum non posuere. Phasellus egestas urna posuere ex porta, vitae ultrices dui lacinia. Mauris porta eu ante sed malesuada. Etiam ultrices interdum accumsan. Nullam id commodo sem.

		Nunc vestibulum in nisi sed condimentum. Mauris semper id orci quis sodales. Morbi viverra dignissim turpis at placerat. Praesent tincidunt enim in tellus feugiat ullamcorper. Aenean nulla enim, vulputate quis viverra ac, eleifend eu ipsum. In feugiat lorem volutpat lorem porttitor aliquam. Pellentesque metus enim, porttitor non maximus ut, ornare eu augue. Proin egestas purus eu justo laoreet, eu consequat tellus pulvinar. Curabitur accumsan nulla id tellus fermentum, vitae dapibus risus molestie. Nulla id purus orci.

		Nunc id nulla sed nisl consequat iaculis ut eu arcu. Proin sit amet ornare velit, ac maximus tortor. Maecenas eget dignissim tortor. Nullam porttitor erat eu augue rutrum volutpat a at mi. Quisque maximus egestas magna, vel sodales magna viverra in. Pellentesque vitae fringilla dui. Donec ullamcorper laoreet elit eu tempor. Curabitur consequat, justo sed aliquam vulputate, neque libero sodales tortor, elementum volutpat lectus lectus non est.

		Donec et lacinia ex. Maecenas tincidunt consectetur velit at vestibulum. Nullam sit amet justo a arcu varius semper. Nulla facilisi. Sed eu mauris maximus, pulvinar massa ac, convallis lorem. Nulla ut sem fermentum felis consectetur pretium ut ac neque. Fusce viverra hendrerit feugiat.

		Ut pretium, elit quis venenatis egestas, ante erat cursus nunc, non pulvinar tortor lorem in quam. Nam quis diam id neque mollis bibendum. Curabitur id tincidunt purus, nec rutrum velit. Nam sodales augue nunc, at fringilla risus aliquet vitae.`
	}
]